apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgChwZirI8hbeDCVnBRYvz02trqbwkwItzaZus4NWFKDWGLLVdyJJ8HaLlPXQPOPZjQeOPhEP/GzQUHJGTcS79ovxsOTeRJ/YLrvGhxdm4oU8snPrA9pxoz32JVdfD1nIguGK7dmJszKSTz7P4UE2o/+WvruKcsuEBAiCRkO8F52JzhgdjrcSCWQ68uJL9+YlK1VF6LG85jUXzBFTbR5M77TDsE37deysEU1N1RjwTwQxlUy7aiD4Vm7J3oCQTZUthw047Jzelq6W1EfdpTDtPlTlaP3btbbRE4r7BIfSy++3Xkn9gjv5o1ZmQF1i1NgJnJms1zLNU/v6dlfIGEbM7TfEa/RqrK9kmTgxdx57eRug5PysrO4xEKGQ7Zs5RR5YmUbOnkjs+bbnEwRktr1fQXSfYu8v5zdpzNw2dZcRQW+jdeVwStLA7hDEQQ6I1ePUgv5Uh7P9DLLI4siMSZNGWVOBCyzDVteSKWzN6knWB1hqnbWBJ0x/zOaux0S0MAk/VDkusHNOYh2SvIK8yiooZF73qj5b7HU1uH6NZRtpzAgUvGRccsZXqUWDcNGe9B5sVxAYox2XsRKVoBgWqZ011HuXk29MzK4MOiuTfEK1L2lPNN/bAvmNgBQwFTIhRu6PV8dmMc2W+GoMWKn/R4CDnIeL0UtnNlG879euAJGBa3lmqAFjQe3GrjmbvvFIhWj6f2bBUIZD1KgWmEl47g+iRPTTVFVbg==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
