apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAbEejjCx1EvLsRNjkSEbIQ4CdrK6JiTku3QgQJCURKMWfjA6qkSwqyehiEv3nQciLsoz1SZxS2/dDXbK1w0eYzw/99W/mMTiVtFdAlLRUYWz/jD5MfSR8aZ7K+wj3gtVAEQerDkw3TcoiTvf/pFPQS9OMXYde1bR/h4Ue/+RT7oOcY52EJbUw4dWQMOmmwTMxN0S3qOVLe8HrzTk+qXkYR3hjLWNJW1z9XquD/6YIHVyXuNGpzuHuT//i4VQ5lFw0Intv7J/mfhieiV05dX/HUna+5xHUJJcurLy/99YZKWUIWnsnCDChT4HLN2vp3yXydC1NEhKePBBJmh3BnNEFGGQv2+aaf/fEsiBqhzWcEd2cuCEj0pmSd4H1VCacEUA8rPQtpQKRU6OBmoIiOeL8cYgsK7IyVGPf8OzGBHcy1tJC2kXSwxwiM6AbKAbC/7nqVJrnYHtMIQps+n4lqSkhk9lBnFHDiRxUSG1RM50SdPoYLqZLn8oKF3j0p4z2uU9L7ylg3UNnb97vYcPWkbtthilk3S23ChfmoyueenyYcZPhXX7J6rUCEciIr/4/4Lvdk+p5Ta02fG3nn/LqRxNCV+aklS3Vo6DjAFccVNyzd0cCNYikVQi34+Fjrmjjptoee/RSm8DZmHMxOmrD+6ajdJkdWauTKJeUcDc55fVWbxPXaEZvACpvgHjOJS0UUn1fmlUQOb4KveJOVgg/q6r3W1Kou4g==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
